# AWS CodeBuild buildspec for Primer Design Automation Pipeline
# Builds Docker image, pushes to ECR, and deploys to App Runner

version: 0.2

# Environment variables (set in CodeBuild project)
# Required:
#   - AWS_ACCOUNT_ID: AWS account ID
#   - AWS_DEFAULT_REGION: Target region (e.g., ap-southeast-1)
#   - IMAGE_REPO_NAME: ECR repository name (e.g., primer-design)
#   - IMAGE_TAG: Image tag (default: latest)

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - echo "Region: $AWS_DEFAULT_REGION"
      - echo "Account: $AWS_ACCOUNT_ID"
      - echo "Repository: $IMAGE_REPO_NAME"

      # Login to ECR
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

      # Set image URI and tag
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:-latest}
      - SHORT_SHA=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)

      - echo "Repository URI: $REPOSITORY_URI"
      - echo "Image Tag: $IMAGE_TAG"
      - echo "Short SHA: $SHORT_SHA"

  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Building the Docker image..."

      # Build Docker image
      - docker build -t $IMAGE_REPO_NAME:latest .
      - docker tag $IMAGE_REPO_NAME:latest $REPOSITORY_URI:latest
      - docker tag $IMAGE_REPO_NAME:latest $REPOSITORY_URI:$SHORT_SHA

      - echo "Build completed on $(date)"

  post_build:
    commands:
      - echo "Pushing Docker images to ECR..."

      # Push both latest and SHA-tagged images
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$SHORT_SHA

      - echo "Image pushed successfully:"
      - echo "  $REPOSITORY_URI:latest"
      - echo "  $REPOSITORY_URI:$SHORT_SHA"

      # Optional: Trigger App Runner deployment (if APP_RUNNER_SERVICE_ARN is set)
      - |
        if [ ! -z "$APP_RUNNER_SERVICE_ARN" ]; then
          echo "Triggering App Runner deployment..."
          aws apprunner start-deployment --service-arn $APP_RUNNER_SERVICE_ARN --region $AWS_DEFAULT_REGION
          echo "App Runner deployment triggered"
        else
          echo "APP_RUNNER_SERVICE_ARN not set, skipping auto-deployment"
        fi

      # Write image definitions for deployment
      - printf '[{"name":"%s","imageUri":"%s"}]' $IMAGE_REPO_NAME $REPOSITORY_URI:$SHORT_SHA > imagedefinitions.json
      - cat imagedefinitions.json

# Artifacts (for downstream deployment systems)
artifacts:
  files:
    - imagedefinitions.json

# Cache Docker layers for faster builds
cache:
  paths:
    - '/root/.docker/**/*'
